### ISSUE TITLE
Why Revel ?

### ISSUE THREAD

**Issue by boopathi** [nobelium/dalalstreet#1]
Revel is highly opinionated approach to dev. Lets use Gorilla toolkit or if we want a framework, we'll use martini.

**Comment by nobelium** [comment]
Compiling templates and cacheing it is a bit low level task and I wanted a framework to handle all those things. Its unnecessarily distracting from the main objective of building the app. I wanted something which does those things for me.
In short, Gorilla is the best choice if we are planning on building a SOA. Since all that we want is a web app, building each part of the service is like reinventing the wheel. We can also start over with Martini if you want.

**Comment by boopathi** [comment]
Martini it is. I've not tried it extensively yet!

**Comment by boopathi** [comment]
http://www.reddit.com/r/golang/comments/25oxg0/three_reasons_you_should_not_use_martini/

**Comment by nobelium** [comment]
Well, sticking to gorilla!!
